### ISSUE TITLE
Apply netbox-plugin to your repo's github topic

### ISSUE THREAD

**Issue by ryanmerolle** [ffddorf/netbox-vault-secrets#10]
This is a great idea for a netbox-plugin.  Thought its not fully packaged with pypi and such, I say you should tag your repo with the github topic [netbox-plugin](https://github.com/topics/netbox-plugin).

On a side note, I have always thought a Hashicorp vault plugin made perfect sense.  Ha I just wrote it down in a list of [plugin candidates](https://github.com/netbox-community/netbox/discussions/8364) I have heard mentioned in passing quite a bit.

**Comment by mraerino** [comment]
Thanks, done!
