### ISSUE TITLE
Object not found in Vault

### ISSUE THREAD

**Issue by lukap357** [ffddorf/netbox-vault-secrets#12]
![image](https://user-images.githubusercontent.com/60240220/154918452-aadafea9-5f5d-4e12-a9f5-6f24970d9b98.png)

Plugin config set to:

PLUGINS_CONFIG = {
    "netbox_vault_secrets": {
        "api_url": "http://127.0.0.1:8200/", # can be relative

Do I need to create the engine in Vault or does the plugin do it? Or do I need to add the path to the config?

**Comment by kemeris2000** [comment]
Here is my config:

    "netbox_vault_secrets": {
        "api_url": "https://xxx.xxx.com", # can be relative
        "kv_mount_path": "v1/password/"  # optional
    }

and I had to manually create KV v2 secrets engine named "password/"

**Comment by lukap357** [comment]
Thanks, it works like that.
