### ISSUE TITLE
Has plugin Netbox v3.1.10 compatibility or missconfig?

### ISSUE THREAD

**Issue by Dees7** [ffddorf/netbox-vault-secrets#16]
Hello.

I try install plugin and use vault. Vault was installed with [manual](https://learn.hashicorp.com/collections/vault/getting-started) and dev server (vault server -dev)

my config:
```
PLUGINS_CONFIG = {
    "netbox_vault_secrets": {
        "api_url": "http://127.0.0.1:8200", # can be relative
        "kv_mount_path": "/v1/secret",  # optional
        "secret_path_prefix": "/netbox",  # optional
    }}
```

Now I open any device and see
![изображение](https://user-images.githubusercontent.com/14229113/161374730-6e3c455f-294b-4c74-b576-9982d65365a7.png)

Has plugin Netbox v3.1.10 compatibility or my missconfig?

**Comment by Dees7** [comment]
Looks like there is no file netbox_vault_secrets/index.js

**Comment by Dees7** [comment]
I was able build index.js and run it. 
Works greate! thanks!

**Comment by kunamashina** [comment]
And how did you build it exactly? I have the same problem

**Comment by Dees7** [comment]
Clone repo
and then  npm install, npm build

**Comment by kunamashina** [comment]
I confirm - this worked for me.

npm install
npm run build

on my installation both index.js files had to be copied into /netbox/static/netbox_vault_secrets/ to enable the plugin communication

Thank you very much for your assistance. I am very grateful and appreciative of your time taken to write this missing step
