### ISSUE TITLE
Error start Docker UP

### ISSUE THREAD

**Issue by sd166** [ffddorf/netbox-vault-secrets#9]
netbox_1       | Creating /opt/netbox/venv/lib/python3.9/site-packages/netbox-vault-secrets.egg-link (link to .)
netbox_1       | netbox-vault-secrets 0.0.1 is already the active version in easy-install.pth
netbox_1       |
netbox_1       | Installed /src
netbox_1       | Processing dependencies for netbox-vault-secrets==0.0.1
netbox_1       | Finished processing dependencies for netbox-vault-secrets==0.0.1
netbox_1       | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1       | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1       | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1       | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1       | Traceback (most recent call last):
netbox_1       |   File "/opt/netbox/netbox/manage.py", line 10, in <module>
netbox_1       |     execute_from_command_line(sys.argv)
netbox_1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
netbox_1       |     utility.execute()
netbox_1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute
netbox_1       |     settings.INSTALLED_APPS
netbox_1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
netbox_1       |     self._setup(name)
netbox_1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
netbox_1       |     self._wrapped = Settings(settings_module)
netbox_1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
netbox_1       |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox_1       |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox_1       |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox_1       |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox_1       |   File "/opt/netbox/netbox/netbox/settings.py", line 593, in <module>
netbox_1       |     plugin = importlib.import_module(plugin_name)
netbox_1       |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox_1       |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox_1       |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox_1       |   File "/src/netbox_vault_secrets/__init__.py", line 7, in <module>
netbox_1       |     class VaultSecretsConfig(PluginConfig):
netbox_1       |   File "/src/netbox_vault_secrets/__init__.py", line 8, in VaultSecretsConfig
netbox_1       |     name = pkg_info.name
netbox_1       |   File "/opt/netbox/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2819, in __getattr__
netbox_1       |     return getattr(self._provider, attr)
netbox_1       | AttributeError: 'PathMetadata' object has no attribute 'name'
netbox_1       | AttributeError: 'PathMetadata' object has no attribute 'name'
netbox_1       | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox_1       | ⏳ Waiting on DB... (0s / 30s)
netbox_1       | AttributeError: 'PathMetadata' object has no attribute 'name'
netbox_1       | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox_1       | ⏳ Waiting on DB... (3s / 30s)
netbox_1       | AttributeError: 'PathMetadata' object has no attribute 'name'
netbox_1       | [ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
netbox_1       | ⏳ Waiting on DB... (6s / 30s)

**Comment by mraerino** [comment]
this should have been resolved by https://github.com/ffddorf/netbox-vault-secrets/pull/8
